In [1]:
import pandas as pd

users = pd.read_csv("resources/data/user_dataset.csv")

In [2]:
users.head(5)

user_no  user_id user_gender  user_age  buy_count  cheese_rank  \
0        0  2391853           M        40          1          8.0   
1        1  1799897           F        40          1          8.0   
2        2  1614947           F        50          1         10.0   
3        3  1614947           F        50          1         10.0   
4        4  1614947           F        50          5         14.0   

   cheese_code cheese_id cheese_brand cheese_name cheese_texture cheese_types  \
0            8        p8         프란시아      리코타 치즈          후레쉬치즈         자연치즈   
1            8        p8         프란시아      리코타 치즈          후레쉬치즈         자연치즈   
2           10       p10         푸글리제        모짜렐라          후레쉬치즈         자연치즈   
3           10       p10         푸글리제        모짜렐라          후레쉬치즈         자연치즈   
4           15       p14          콜롬보        모짜렐라          후레쉬치즈         자연치즈   

  cheese_category cheese_one_price  gender  age_group  cheese_category_code  \
0             리코타           4,600원       0          3                     3   
1             리코타           4,600원       1          3                     3   
2            모짜렐라           5,500원       1          4                     1   
3            모짜렐라           5,500원       1          4                     1   
4            모짜렐라           4,900원       1          4                     1   

   cheese_texture_code brand  brand_code  
0                    1  프란시아          15  
1                    1  프란시아          15  
2                    1  푸글리제          30  
3                    1  푸글리제          30  
4                    1   콜롬보          28

In [3]:
# user_X_train_set = user_X_train.drop('user_id', axis = 1)
users['cheese_id'] = users['cheese_id'].str.replace('p','')
users['cheese_one_price'] = users['cheese_one_price'].str.replace(',', '')
users['cheese_one_price'] = users['cheese_one_price'].str.replace('원', '')
users = users.astype({'cheese_one_price': int})

# user_X_trian_set = user_X_train_set.astype({'cheese_one_price': int})

## Train, Test 데이터 셋 만들기

In [4]:
from sklearn.model_selection import train_test_split

X_user = users[['user_age', 'gender', 'buy_count', 'cheese_rank', 'cheese_texture_code', 'brand_code', 'cheese_one_price']]
y_user = users[['cheese_category_code']]

X_user_train, X_user_test, y_user_train, y_user_test = train_test_split(X_user, y_user, test_size = 0.3, random_state = 32)

In [5]:
# std 바꿔서 fitting

import sklearn.svm as svm
import sklearn.metrics as mt
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler

# 표준화
std = StandardScaler()
# std.fit(X_train)

X_user_train_std = std.fit_transform(X_user_train)
X_user_test_std = std.transform(X_user_test)
print(X_user_train_std)


[[-0.58733941  0.42761125 -0.01216164 ... -0.48303349 -0.48402246
  -0.85734486]
 [-0.58733941  0.42761125 -0.01216164 ... -0.48303349 -0.48402246
  -0.85734486]
 [ 1.74261025  0.42761125 -0.26129191 ... -0.48303349  0.73833953
  -0.07477204]
 ...
 [-0.58733941  0.42761125  0.23696863 ...  0.57380955  1.96070152
  -0.43072489]
 [-0.58733941  0.42761125 -0.26129191 ... -0.48303349 -1.04818953
   0.64236827]
 [ 1.74261025  0.42761125 -0.26129191 ...  0.57380955  1.96070152
  -0.43072489]]


In [6]:
from sklearn.preprocessing import MinMaxScaler

ns = MinMaxScaler()
ns.fit(X_user_train)

X_user_train_ns = ns.transform(X_user_train)
X_user_test_ns = ns.transform(X_user_test)
print(X_user_train_ns)

[[0.33333333 1.         0.00840336 ... 0.         0.34146341 0.        ]
 [0.33333333 1.         0.00840336 ... 0.         0.34146341 0.        ]
 [0.66666667 1.         0.         ... 0.         0.65853659 0.2485453 ]
 ...
 [0.33333333 1.         0.01680672 ... 0.2        0.97560976 0.1354946 ]
 [0.33333333 1.         0.         ... 0.         0.19512195 0.47630923]
 [0.66666667 1.         0.         ... 0.2        0.97560976 0.1354946 ]]


In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_user_train, y_user_train)

# 예측
y_pred = forest.predict(X_user_test)
print(y_pred)
# print(list(y_test))

print('정확도 : ', metrics.accuracy_score(y_user_test, y_pred))

print("특성 중요도: \n{}".format(forest.feature_importances_))

/home/bitai/anaconda3/envs/cheese-ai/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


[ 1  1  5 ...  1  1 11]
정확도 :  0.9996384017356716
특성 중요도: 
[0.00271529 0.00078586 0.00717357 0.35812326 0.17081001 0.17562203
 0.28476999]


In [9]:
from sklearn.model_selection import train_test_split

X_user_2 = users[['buy_count', 'cheese_rank', 'cheese_texture_code', 'brand_code', 'cheese_one_price']]
y_user_2 = users[['cheese_category_code']]

X_user_train, X_user_test, y_user_train, y_user_test = train_test_split(X_user_2, y_user_2, test_size = 0.3, random_state = 32)

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_user_train, y_user_train)

# 예측
y_pred = forest.predict(X_user_test)
print(y_pred)
# print(list(y_test))

print('정확도 : ', metrics.accuracy_score(y_user_test, y_pred))

print("특성 중요도: \n{}".format(forest.feature_importances_))

/home/bitai/anaconda3/envs/cheese-ai/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


[ 1  1  5 ...  1  1 11]
정확도 :  1.0
특성 중요도: 
[0.00335012 0.38205243 0.19814272 0.15837354 0.25808119]


## 텐서플로우 - 다항 로지스틱 회귀분석

### y값 OHE로 바꾸고 다시 모델링 학습하기

In [11]:
import pandas as pd

y_user_train_ohe = pd.get_dummies(y_user_train['cheese_category_code'])
y_user_test_ohe = pd.get_dummies(y_user_test['cheese_category_code'])

In [12]:
y_user_train_ohe.head(3)

1   2   3   4   5   6   7   8   9   10  11
3312    1   0   0   0   0   0   0   0   0   0   0
21971   1   0   0   0   0   0   0   0   0   0   0
2347    0   0   1   0   0   0   0   0   0   0   0

In [18]:
import tensorflow.compat.v1 as tf

# 변수 정의
with tf.Session() as sess:
    x = tf.placeholder(tf.float32, shape = [None, 7])
    y = tf.placeholder(tf.float32, shape = [None, 11])

    nb_classes = 11

    w = tf.Variable(tf.random_normal([7, 11]))
    b = tf.Variable(tf.random_normal([11]))
    
    hf = tf.nn.sotfmax((tf.matmul(x, w) + b))
    cost = tf.reduce_mean( - tf.reduce_sum(y * tf.log(hf), axis = 1))
    
    #모델 생성
    opt = tf.train.GradientDescentOptimizer(0.1).minimize(cost)
    
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        cv = sess.run([opt,cost], feed_dict = {x:x_data, y:y_data})
        if step %1000==0:
            